### ISSUE TITLE
Exact matches are not preferred

### ISSUE THREAD

**Issue by dillonhafer** [hashrocket/vim-hr-psql#2]
Given two tables:

```sql
create table targets (id serial primary key);
create table campaigns_targets (id serial primary key);
```

And a ruby file:

```ruby
class Model
  def targets    
  end
end
```

When the cursor is on the word `targets`

Then the table `campaigns_targets` is shown, but I expected the `targets` table to be shown (being an exact match)

**Comment by dillonhafer** [comment]
This also affects the `:Pgtable` command

**Comment by chriserin** [comment]
Thanks Dillon!  I'll follow up on this on Friday.

-chris

**Comment by chriserin** [comment]
Hi @dillonhafer I think this is solved with https://github.com/hashrocket/vim-hr-psql/commit/1f0d01cc06afd4fd5d5dedaa85da6c169c723bd6

Thanks for using vim-hr-psql!
